domains:
    - name: test.com
      records:
        - name: aaa.test.com
          type: A
          value: 192.168.1.1
          ttl: 300
gin:
    host: 0.0.0.0
    idle_timeout: 15s
    max_multipart_memory: 10485760
    mode: debug
    port: 8080
    read_timeout: 5s
    write_timeout: 10s
jwt:
    audience: api-users
    expire_hours: 2
    issuer: dnsm
    refresh_hours: 24
    secret_key: default-secret-key-32bytes-long-1234
    signing_method: HS256
login:
    password: admin123
    username: admin
server:
    host: 0.0.0.0
    port: 53
upstream:
    - 223.5.5.5:53
    - 10.168.10.60:53
